In [247]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression as LR

In [248]:
data=pd.read_csv('training_prepared.csv')

In [249]:
logistic_model=LR()

In [250]:
data

,Unnamed: 0,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,Location_SydneyAirport,Location_Tuggeranong,Location_WaggaWagga,Location_Watsonia,Location_Williamtown,Location_Wollongong,Location_nan,RainToday_No,RainToday_Yes,RainToday_nan
0,0,13.4,22.9,0.6,NaN,NaN,44.0,20.0,24.0,71.0,...,0,0,0,0,0,0,0,1,0,0
1,1,7.4,25.1,0.0,NaN,NaN,44.0,4.0,22.0,44.0,...,0,0,0,0,0,0,0,1,0,0
2,2,12.9,25.7,0.0,NaN,NaN,46.0,19.0,26.0,38.0,...,0,0,0,0,0,0,0,1,0,0
3,3,9.2,28.0,0.0,NaN,NaN,24.0,11.0,9.0,45.0,...,0,0,0,0,0,0,0,1,0,0
4,4,17.5,32.3,1.0,NaN,NaN,41.0,7.0,20.0,82.0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70235,70235,19.2,29.1,0.0,NaN,NaN,52.0,22.0,37.0,61.0,...,0,0,0,0,0,0,0,1,0,0
70236,70236,20.0,28.2,8.2,NaN,NaN,50.0,20.0,31.0,75.0,...,0,0,0,0,0,0,0,0,1,0
70237,70237,19.8,29.1,0.0,NaN,NaN,41.0,24.0,31.0,62.0,...,0,0,0,0,0,0,0,1,0,0
70238,70238,18.8,28.3,3.4,NaN,NaN,33.0,17.0,24.0,69.0,...,0,0,0,0,0,0,0,0,1,0
70239,70239,17.8,28.6,0.0,NaN,NaN,30.0,15.0,19.0,60.0,...,0,0,0,0,0,0,0,1,0,0

In [251]:
data.fillna(0,inplace=True)
data

,Unnamed: 0,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,Location_SydneyAirport,Location_Tuggeranong,Location_WaggaWagga,Location_Watsonia,Location_Williamtown,Location_Wollongong,Location_nan,RainToday_No,RainToday_Yes,RainToday_nan
0,0,13.4,22.9,0.6,0.0,0.0,44.0,20.0,24.0,71.0,...,0,0,0,0,0,0,0,1,0,0
1,1,7.4,25.1,0.0,0.0,0.0,44.0,4.0,22.0,44.0,...,0,0,0,0,0,0,0,1,0,0
2,2,12.9,25.7,0.0,0.0,0.0,46.0,19.0,26.0,38.0,...,0,0,0,0,0,0,0,1,0,0
3,3,9.2,28.0,0.0,0.0,0.0,24.0,11.0,9.0,45.0,...,0,0,0,0,0,0,0,1,0,0
4,4,17.5,32.3,1.0,0.0,0.0,41.0,7.0,20.0,82.0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70235,70235,19.2,29.1,0.0,0.0,0.0,52.0,22.0,37.0,61.0,...,0,0,0,0,0,0,0,1,0,0
70236,70236,20.0,28.2,8.2,0.0,0.0,50.0,20.0,31.0,75.0,...,0,0,0,0,0,0,0,0,1,0
70237,70237,19.8,29.1,0.0,0.0,0.0,41.0,24.0,31.0,62.0,...,0,0,0,0,0,0,0,1,0,0
70238,70238,18.8,28.3,3.4,0.0,0.0,33.0,17.0,24.0,69.0,...,0,0,0,0,0,0,0,0,1,0
70239,70239,17.8,28.6,0.0,0.0,0.0,30.0,15.0,19.0,60.0,...,0,0,0,0,0,0,0,1,0,0

In [252]:
data['RainTomorrow']=data['RainTomorrow'].apply(lambda s: 1 if s=='Yes' else 0)
labels=data['RainTomorrow']
features=data.drop('RainTomorrow',axis=1)
features_arr=np.array(features)
print(np.where(np.isnan(features_arr)))

(array([], dtype=int64), array([], dtype=int64))

In [253]:
from sklearn.model_selection import train_test_split

In [254]:
train,test,train_labels,test_labels = train_test_split(features_arr, labels, test_size = 0.25, random_state = 30)

In [255]:
logistic_model.fit(train,train_labels)

/home/vlad333rrty/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [261]:
pred=logistic_model.predict(test)

In [262]:
from sklearn.metrics import accuracy_score, r2_score,log_loss

In [267]:
accuracy_score(pred,test_labels)

0.9773917995444191